trigger:
    branches:
        include:
            - '*'
    tags:
        include:
            - '*'

resources:
    containers:
        - container: tarpaulin
          image: xd009642/tarpaulin:latest-nightly
          options: --security-opt seccomp=unconfined

jobs:
    - job: Linux
      pool:
          vmImage: 'ubuntu-16.04'
      steps:
          - script: |
              curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
              echo '##vso[task.setvariable variable=PATH]$(PATH):$(HOME)/.cargo/bin'
            displayName: Install rustup

          - script: |
              cargo test
            displayName: Run test

          - script: |
              chmod 777 ./target
              make release_lnx
              cp *.zip $(Build.ArtifactStagingDirectory)
            displayName: Build release binary
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

          - task: PublishBuildArtifacts@1
            inputs:
                artifactName: 'Linux'
                pathtoPublish: $(Build.ArtifactStagingDirectory)
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

    - job: macOS
      pool:
          vmImage: 'macos-10.13'
      steps:
          - script: |
              curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
              echo '##vso[task.setvariable variable=PATH]$(PATH):$(HOME)/.cargo/bin'
            displayName: Install rustup

          - script: |
              cargo test
            displayName: Run test

          - script: |
              make release_mac
              cp *.zip $(Build.ArtifactStagingDirectory)
            displayName: Build release binary
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

          - task: PublishBuildArtifacts@1
            inputs:
                artifactName: 'macOS'
                pathtoPublish: $(Build.ArtifactStagingDirectory)
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

    - job: Windows
      pool:
          vmImage: 'vs2017-win2016'
      steps:
          - script: |
              curl -sSf -o rustup-init.exe https://win.rustup.rs
              rustup-init.exe -y --default-toolchain stable
              set PATH=%PATH%;%USERPROFILE%\.cargo\bin
              echo '##vso[task.setvariable variable=PATH]%PATH%;%USERPROFILE%\.cargo\bin'
            displayName: Install rustup

          - script: |
              cargo test
            displayName: Run test

          - script: |
              make release_win
              cp *.zip $(Build.ArtifactStagingDirectory)
            displayName: Build release binary
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

          - task: PublishBuildArtifacts@1
            inputs:
                artifactName: 'Windows'
                pathtoPublish: $(Build.ArtifactStagingDirectory)
            condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

    - job: Coverage
      pool:
          vmImage: 'ubuntu-16.04'
      container: tarpaulin
      steps:
          - script: |
              cargo tarpaulin -v --out Xml
              curl -s https://codecov.io/bash -o .codecov && chmod +x .codecov
              ./.codecov -B "${BUILD_SOURCEBRANCHNAME:-}" \
                         -C "${BUILD_SOURCEVERSION:-}" \
                         -P "${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER:-}" \
                         -b "${BUILD_BUILDID:-}" \
                         -K -n "report name"
            displayName: Run tarpaulin
            env:
                CODECOV_TOKEN: $(CODECOV_TOKEN)

    - job: Release
      dependsOn:
          - Linux
          - macOS
          - Windows
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      steps:
          - task: DownloadBuildArtifacts@0
            inputs:
                downloadType: 'specific'
                itemPattern: '**'
                downloadPath: $(Build.ArtifactStagingDirectory)

          - task: GitHubRelease@0
            inputs:
                gitHubConnection: 'dalance'
                repositoryName: 'dalance/git-skel'
                tagSource: 'auto'
                releaseNotesSource: 'input'
                releaseNotes: '[Changelog](https://github.com/dalance/git-skel/blob/master/CHANGELOG.md)'
                assets: '$(Build.ArtifactStagingDirectory)/*/*'
                assetUploadMode: 'replace'
                isDraft: false
                isPreRelease: false
                addChangeLog: false
            displayName: Release to GitHub
